
!INCLUDE ..\predef.mk

TESTS = \
    $(BINDIR)\re$(xEXE) \

_TESTS = \
    $(BINDIR)\safeformat$(xEXE) \
    $(BINDIR)\program$(xEXE) \
    $(BINDIR)\buffer$(xEXE) \
    $(BINDIR)\string$(xEXE) \
    $(BINDIR)\dicto$(xEXE) \
    $(BINDIR)\array$(xEXE) \
    $(BINDIR)\program$(xEXE) \
    $(BINDIR)\file$(xEXE) \
    $(BINDIR)\bigint$(xEXE) \
    $(BINDIR)\bigint.txt \

!INCLUDE ..\rules.mk



