
!INCLUDE ..\predef.mk

#TOOLS=  \
#    $(TOOLDIR)\aesxex.exe \

TESTS= 	\
    $(BINDIR)\sha1.exe \
    $(BINDIR)\hmacsha1.exe \

TESTS_= \
    $(BINDIR)\md5.exe \
    $(BINDIR)\sha1.exe \
    $(BINDIR)\sha2.exe \
    $(BINDIR)\hmacmd5.exe \
    $(BINDIR)\hmacsha1.exe \
    $(BINDIR)\hmacsha2.exe \
    $(BINDIR)\random.exe \
    $(BINDIR)\aes.exe \
    $(BINDIR)\blowfish.exe \
    $(BINDIR)\rsa.exe \
    $(BINDIR)\rsagen.exe \
    $(BINDIR)\prime.exe \
    $(BINDIR)\modpow2.exe \
    

!INCLUDE ..\rules.mk 